from typing import Protocol

class PdfConverter(Protocol):
    async def create(self) -> None: ...
    async def convert_to_pdf(self, html_content: str) -> bytes: ...
    async def close(self) -> None: ...